---
# Simple web application for TLS testing
# This is the backend that will be accessed via HTTPS through Ingress

apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: tls-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      # Init container to create custom HTML
      initContainers:
        - name: setup-html
          image: busybox
          command:
            - sh
            - -c
            - |
              cat > /html/index.html <<'EOF'
              <!DOCTYPE html>
              <html>
              <head>
                  <title>Secure App</title>
                  <style>
                      body {
                          font-family: Arial;
                          text-align: center;
                          padding: 50px;
                          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                          color: white;
                      }
                      .container {
                          background: rgba(255, 255, 255, 0.1);
                          padding: 40px;
                          border-radius: 15px;
                          backdrop-filter: blur(10px);
                      }
                      .lock { font-size: 60px; }
                      .success { color: #4ade80; font-weight: bold; }
                  </style>
              </head>
              <body>
                  <div class="container">
                      <div class="lock">🔒</div>
                      <h1>HTTPS is Working!</h1>
                      <p class="success">✓ TLS Terminated at Ingress</p>
                      <p>Connection: <span id="protocol"></span></p>
                      <p>Host: <span id="host"></span></p>
                      <script>
                          document.getElementById('protocol').textContent = window.location.protocol;
                          document.getElementById('host').textContent = window.location.hostname;
                      </script>
                  </div>
              </body>
              </html>
              EOF
          volumeMounts:
            - name: html
              mountPath: /html
      volumes:
        - name: html
          emptyDir: {}

---
# Service to expose the application
# Ingress will route HTTPS traffic to this Service

apiVersion: v1
kind: Service
metadata:
  name: secure-app
  namespace: tls-demo
spec:
  selector:
    app: secure-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
# What this creates:
#
# Native resources:
#   - Deployment: secure-app (manages 2 nginx pods)
#   - ReplicaSet: (created by Deployment)
#   - Pods: secure-app-xxxxx (2 replicas)
#   - Service: secure-app (ClusterIP, internal only)
#
# Traffic flow (after configuring Ingress):
#   Client (Browser)
#     ↓ HTTPS (port 443)
#   Ingress Controller (192.168.11.240)
#     ↓ TLS termination using Secret
#     ↓ HTTP (port 80, unencrypted internal traffic)
#   Service: secure-app
#     ↓ Load balances
#   Pods: secure-app-xxxxx
#
# Important notes:
#   - Pods serve HTTP (port 80), NOT HTTPS
#   - TLS is terminated at Ingress (edge termination)
#   - Internal cluster traffic is unencrypted (HTTP)
#   - For end-to-end TLS, pods would also need certificates (complex)
#
# Inspect with:
#   kubectl get all -n tls-demo
#   kubectl get deployment,svc,pods -n tls-demo
#   kubectl describe service secure-app -n tls-demo
